# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-lambda-function
  description: A module for launching Lambda Fuctions
  homepage: https://cloudposse.com/accelerate
  topics: ""



